create table if not exists public.programs (
  id text primary key check (id in ('folk', 'gita-life')),
  name text not null,
  status text not null default 'Active' check (status in ('Active', 'Inactive')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

insert into public.programs (id, name)
values
  ('folk', 'FOLK Chennai'),
  ('gita-life', 'Gita Life')
on conflict (id) do update
set name = excluded.name;

create table if not exists public.staff_memberships (
  id uuid primary key default gen_random_uuid(),
  program_id text not null references public.programs(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  email text not null,
  airtable_user_id text not null,
  name text,
  role text not null check (role in ('Admin', 'Preacher', 'Volunteer')),
  status text not null check (status in ('Active', 'Inactive', 'Suspended', 'Revoked')),
  location_ids text[] not null default '{}'::text[],
  assigned_preacher_airtable_user_id text,
  last_synced_at timestamptz not null default now(),
  revoked_at timestamptz,
  sync_source text not null default 'airtable',
  sync_state text not null default 'ok' check (sync_state in ('ok', 'stale', 'failed')),
  sync_error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (program_id, user_id)
);

create unique index if not exists staff_memberships_program_email_uidx
on public.staff_memberships (program_id, lower(email));

create index if not exists staff_memberships_program_role_idx
on public.staff_memberships (program_id, role);

create index if not exists staff_memberships_airtable_user_id_idx
on public.staff_memberships (airtable_user_id);

alter table public.staff_memberships enable row level security;

create table if not exists public.airtable_identities (
  id uuid primary key default gen_random_uuid(),
  program_id text not null references public.programs(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  airtable_base_id text not null,
  airtable_user_id text not null,
  email text not null,
  last_synced_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (program_id, airtable_user_id),
  unique (program_id, user_id)
);

create index if not exists airtable_identities_program_email_idx
on public.airtable_identities (program_id, lower(email));

alter table public.airtable_identities enable row level security;

create table if not exists public.airtable_sync_state (
  id uuid primary key default gen_random_uuid(),
  program_id text not null references public.programs(id) on delete cascade,
  source text not null,
  status text not null check (status in ('ok', 'stale', 'failed')),
  last_synced_at timestamptz,
  error_message text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (program_id, source)
);

alter table public.airtable_sync_state enable row level security;

create table if not exists public.audit_events (
  id bigint generated by default as identity primary key,
  program_id text not null references public.programs(id) on delete cascade,
  actor_supabase_user_id uuid references auth.users(id) on delete set null,
  actor_airtable_user_id text,
  actor_role text,
  action text not null,
  target_id text,
  source text not null,
  sync_state text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists audit_events_program_action_created_idx
on public.audit_events (program_id, action, created_at desc);

alter table public.audit_events enable row level security;

alter table public.invite_log
  add column if not exists program_id text references public.programs(id) on delete set null default 'folk';

alter table public.staff_profiles
  add column if not exists program_id text references public.programs(id) on delete set null default 'folk',
  add column if not exists membership_status text default 'Active' check (membership_status in ('Active', 'Inactive', 'Suspended', 'Revoked'));

drop trigger if exists set_programs_updated_at on public.programs;
create trigger set_programs_updated_at
before update on public.programs
for each row execute function public.set_updated_at();

drop trigger if exists set_staff_memberships_updated_at on public.staff_memberships;
create trigger set_staff_memberships_updated_at
before update on public.staff_memberships
for each row execute function public.set_updated_at();

drop trigger if exists set_airtable_identities_updated_at on public.airtable_identities;
create trigger set_airtable_identities_updated_at
before update on public.airtable_identities
for each row execute function public.set_updated_at();

drop trigger if exists set_airtable_sync_state_updated_at on public.airtable_sync_state;
create trigger set_airtable_sync_state_updated_at
before update on public.airtable_sync_state
for each row execute function public.set_updated_at();
