create table if not exists public.staff_profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null unique,
  airtable_user_id text not null,
  name text,
  role text not null check (role in ('Admin', 'Preacher', 'Volunteer')),
  status text not null check (status in ('Active', 'Inactive')),
  last_synced_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists staff_profiles_email_idx on public.staff_profiles (lower(email));
create index if not exists staff_profiles_airtable_user_id_idx on public.staff_profiles (airtable_user_id);

alter table public.staff_profiles enable row level security;

create table if not exists public.invite_log (
  id bigint generated by default as identity primary key,
  invitee_email text not null,
  airtable_user_id text,
  inviter_airtable_user_id text,
  inviter_supabase_user_id uuid references auth.users(id) on delete set null,
  invitee_role text not null check (invitee_role in ('Admin', 'Preacher', 'Volunteer')),
  status text not null check (status in ('pending', 'sent', 'failed', 'accepted')),
  error_message text,
  invited_at timestamptz not null default now(),
  accepted_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists invite_log_invitee_email_idx on public.invite_log (lower(invitee_email));
create index if not exists invite_log_airtable_user_id_idx on public.invite_log (airtable_user_id);

alter table public.invite_log enable row level security;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_staff_profiles_updated_at on public.staff_profiles;
create trigger set_staff_profiles_updated_at
before update on public.staff_profiles
for each row execute function public.set_updated_at();

drop trigger if exists set_invite_log_updated_at on public.invite_log;
create trigger set_invite_log_updated_at
before update on public.invite_log
for each row execute function public.set_updated_at();
